name: Build C++ Docker Image and Push to ACR

on:
  push:
    branches: [main]
    paths:
      - '**'
      - '!README.md'
      - '!docs/**'

# Required for OIDC authentication
permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: todocpp
  IMAGE_NAME: todo-cpp-restful
  RESOURCE_GROUP: todo-cpp-project

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to Azure Container Registry
      run: az acr login --name ${{ env.ACR_NAME }}

    - name: Extract metadata for Docker
      id: meta
      run: |
        echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        
        # Set image tags based on event type
        echo "tags=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest,${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Build C++ Docker image
      run: |
        echo "Building C++ Docker image..."
        echo "Tags: ${{ steps.meta.outputs.tags }}"
        
        # Build with multiple tags
        IFS=',' read -ra TAGS <<< "${{ steps.meta.outputs.tags }}"
        
        BUILD_ARGS=""
        for tag in "${TAGS[@]}"; do
          BUILD_ARGS="$BUILD_ARGS -t $tag"
        done
        
        docker build $BUILD_ARGS \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --label "org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}" \
          --label "org.opencontainers.image.revision=${{ github.sha }}" \
          --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
          .

    - name: Push images to ACR
      run: |
        echo "Pushing images to Azure Container Registry..."
        
        # Push all tags
        IFS=',' read -ra TAGS <<< "${{ steps.meta.outputs.tags }}"
        for tag in "${TAGS[@]}"; do
          echo "Pushing: $tag"
          docker push $tag
        done
        
        echo "All images pushed successfully!"

    - name: Show pushed images
      run: |
        echo "Images pushed to ACR:"
        az acr repository show-tags --name ${{ env.ACR_NAME }} --repository ${{ env.IMAGE_NAME }} --output table
        
    - name: Azure logout
      run: az logout
      if: always()